State.create(name: 'New South Wales', abbrev: 'nsw')
State.create(name: 'South Australia', abbrev: 'sa')
State.create(name: 'Queensland', abbrev: 'qld')
State.create(name: 'Victoria', abbrev: 'vic')
State.create(name: 'Western Australia', abbrev: 'wa')
State.create(name: 'Tasmania', abbrev: 'tas')
State.create(name: 'ACT', abbrev: 'act')
State.create(name: 'Northern Territory', abbrev: 'nt')
